# Generated by Django 4.2.1 on 2023-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserPassword', models.CharField(max_length=500)),
                ('UserRol', models.IntegerField(max_length=10)),
                ('UserStatus', models.BooleanField()),
            ],
        ),
    ]
