import { NavbarComponent } from '../components/navbar/navbar.component';
export interface Competitor {
  id: number,
  bib: number,
  name: string,
  time_seconds: number,
  time_points: number,
  jump1_j4_points: number,
  jump1_j5_points: number,
  jump1_trick: string,
  jump1_dd: number,
  jump2_j4_points: number,
  jump2_j5_points: number,
  jump2_trick: string,
  jump2_dd: number,
  jumps_total: number,
  turns_j1_b: number,
  turns_j1_d: number,
  turns_j2_b: number,
  turns_j2_d: number,
  turns_j3_b: number,
  turns_j3_d: number,
  turns_total: number,
  run_score: number,
  competitor_of: number,
}
